# -*- coding: utf-8 -*-
"""MachineLearning-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aFtxG3TiLGNwVGrY9owh1uen6Y0sT6q
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

df=pd.read_csv("sales.csv")

encoder=LabelEncoder()
df['gender_encoded']=encoder.fit_transform(df['gender'])
df['loyalty_encoded']=encoder.fit_transform(df['loyalty_tier'])
df['country']=encoder.fit_transform(df['country'])
df['channel_encoded']=encoder.fit_transform(df['acquisition_channel'])

#input
x=df[[
    'age',
    'gender_encoded',
    'country',
    'channel_encoded'
]]
#output
y=df['loyalty_encoded']
#train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
predictions=model.predict(x_test)
accuracy=accuracy_score(
    y_test,
    predictions
)
print("Accuracy",accuracy)

matrix=confusion_matrix(
    y_test,
    predictions
)
print("Confusions Matrix")
print(matrix)